insert into address (student_id, house_number, city, state, country, pin) values (1, '7332 Merchant Drive', 'Salt Lake City', 'Utah', 'United States', '84145');
insert into address (student_id, house_number, city, state, country, pin) values (2, '16 Park Meadow Way', 'Bradenton', 'Florida', 'United States', '34210');
insert into address (student_id, house_number, city, state, country, pin) values (3, '3120 Saint Paul Center', 'Arlington', 'Texas', 'United States', '76011');
insert into address (student_id, house_number, city, state, country, pin) values (4, '551 Judy Park', 'Greensboro', 'North Carolina', 'United States', '27425');
insert into address (student_id, house_number, city, state, country, pin) values (5, '717 Armistice Terrace', 'Pocatello', 'Idaho', 'United States', '83206');
insert into address (student_id, house_number, city, state, country, pin) values (6, '64037 Namekagon Circle', 'Monroe', 'Louisiana', 'United States', '71213');
insert into address (student_id, house_number, city, state, country, pin) values (7, '50567 Charing Cross Terrace', 'San Antonio', 'Texas', 'United States', '78285');
insert into address (student_id, house_number, city, state, country, pin) values (8, '967 Mosinee Place', 'Seattle', 'Washington', 'United States', '98195');
insert into address (student_id, house_number, city, state, country, pin) values (9, '761 Truax Lane', 'Wilkes Barre', 'Pennsylvania', 'United States', '18706');
insert into address (student_id, house_number, city, state, country, pin) values (10, '39795 Harper Circle', 'Phoenix', 'Arizona', 'United States', '85099');
insert into address (student_id, house_number, city, state, country, pin) values (11, '42 Lerdahl Pass', 'Topeka', 'Kansas', 'United States', '66629');
insert into address (student_id, house_number, city, state, country, pin) values (12, '4 Old Gate Way', 'Nashville', 'Tennessee', 'United States', '37215');
insert into address (student_id, house_number, city, state, country, pin) values (13, '38394 Hallows Terrace', 'Cleveland', 'Ohio', 'United States', '44197');
insert into address (student_id, house_number, city, state, country, pin) values (14, '98187 David Court', 'Sandy', 'Utah', 'United States', '84093');
insert into address (student_id, house_number, city, state, country, pin) values (15, '6657 East Way', 'Detroit', 'Michigan', 'United States', '48217');
insert into address (student_id, house_number, city, state, country, pin) values (16, '07345 Stoughton Circle', 'Apache Junction', 'Arizona', 'United States', '85219');
insert into address (student_id, house_number, city, state, country, pin) values (17, '42 Bellgrove Crossing', 'Greensboro', 'North Carolina', 'United States', '27409');
insert into address (student_id, house_number, city, state, country, pin) values (18, '6 Schiller Point', 'Valley Forge', 'Pennsylvania', 'United States', '19495');
insert into address (student_id, house_number, city, state, country, pin) values (19, '1501 Arapahoe Way', 'Mesquite', 'Texas', 'United States', '75185');
insert into address (student_id, house_number, city, state, country, pin) values (20, '739 Duke Crossing', 'Tacoma', 'Washington', 'United States', '98442');
insert into address (student_id, house_number, city, state, country, pin) values (21, '25 Lawn Parkway', 'Winston Salem', 'North Carolina', 'United States', '27116');
insert into address (student_id, house_number, city, state, country, pin) values (22, '775 Macpherson Way', 'New York City', 'New York', 'United States', '10045');
insert into address (student_id, house_number, city, state, country, pin) values (23, '0419 Sundown Street', 'Portland', 'Oregon', 'United States', '97271');
insert into address (student_id, house_number, city, state, country, pin) values (24, '1 Anhalt Lane', 'Buffalo', 'New York', 'United States', '14205');
insert into address (student_id, house_number, city, state, country, pin) values (25, '4 Fallview Way', 'Fresno', 'California', 'United States', '93726');
insert into address (student_id, house_number, city, state, country, pin) values (26, '3631 Susan Hill', 'Columbia', 'Missouri', 'United States', '65218');
insert into address (student_id, house_number, city, state, country, pin) values (27, '3 Stone Corner Alley', 'Houston', 'Texas', 'United States', '77090');
insert into address (student_id, house_number, city, state, country, pin) values (28, '777 Nelson Parkway', 'Lafayette', 'Indiana', 'United States', '47905');
insert into address (student_id, house_number, city, state, country, pin) values (29, '0900 Washington Court', 'Naples', 'Florida', 'United States', '34102');
insert into address (student_id, house_number, city, state, country, pin) values (30, '36899 Anthes Terrace', 'Pensacola', 'Florida', 'United States', '32526');
insert into address (student_id, house_number, city, state, country, pin) values (31, '329 Oriole Place', 'Charleston', 'West Virginia', 'United States', '25313');
insert into address (student_id, house_number, city, state, country, pin) values (32, '8 South Court', 'Seattle', 'Washington', 'United States', '98166');
insert into address (student_id, house_number, city, state, country, pin) values (33, '24278 Kropf Alley', 'Dayton', 'Ohio', 'United States', '45470');
insert into address (student_id, house_number, city, state, country, pin) values (34, '08138 Ronald Regan Drive', 'Scranton', 'Pennsylvania', 'United States', '18505');
insert into address (student_id, house_number, city, state, country, pin) values (35, '69 Farragut Circle', 'Lakewood', 'Washington', 'United States', '98498');
insert into address (student_id, house_number, city, state, country, pin) values (36, '39 Straubel Alley', 'Savannah', 'Georgia', 'United States', '31416');
insert into address (student_id, house_number, city, state, country, pin) values (37, '8 Schiller Parkway', 'Sacramento', 'California', 'United States', '94273');
insert into address (student_id, house_number, city, state, country, pin) values (38, '7371 Cardinal Road', 'Fort Lauderdale', 'Florida', 'United States', '33315');
insert into address (student_id, house_number, city, state, country, pin) values (39, '64 Mockingbird Alley', 'Atlanta', 'Georgia', 'United States', '31190');
insert into address (student_id, house_number, city, state, country, pin) values (40, '09917 Arkansas Park', 'Jackson', 'Mississippi', 'United States', '39210');
insert into address (student_id, house_number, city, state, country, pin) values (41, '2 Pine View Junction', 'Oceanside', 'California', 'United States', '92056');
insert into address (student_id, house_number, city, state, country, pin) values (42, '8 Daystar Way', 'Lake Worth', 'Florida', 'United States', '33467');
insert into address (student_id, house_number, city, state, country, pin) values (43, '76526 Maple Wood Hill', 'Shawnee Mission', 'Kansas', 'United States', '66210');
insert into address (student_id, house_number, city, state, country, pin) values (44, '75 Forest Dale Crossing', 'Asheville', 'North Carolina', 'United States', '28805');
insert into address (student_id, house_number, city, state, country, pin) values (45, '5 Sullivan Lane', 'Houston', 'Texas', 'United States', '77293');
insert into address (student_id, house_number, city, state, country, pin) values (46, '0414 Westport Way', 'Tuscaloosa', 'Alabama', 'United States', '35405');
insert into address (student_id, house_number, city, state, country, pin) values (47, '3146 Sachs Drive', 'Houston', 'Texas', 'United States', '77228');
insert into address (student_id, house_number, city, state, country, pin) values (48, '3 Stone Corner Way', 'Asheville', 'North Carolina', 'United States', '28805');
insert into address (student_id, house_number, city, state, country, pin) values (49, '5047 Morningstar Pass', 'Saint Cloud', 'Minnesota', 'United States', '56398');
insert into address (student_id, house_number, city, state, country, pin) values (50, '8 Lake View Way', 'Suffolk', 'Virginia', 'United States', '23436');
insert into address (student_id, house_number, city, state, country, pin) values (51, '3738 Kenwood Avenue', 'San Francisco', 'California', 'United States', '94137');
insert into address (student_id, house_number, city, state, country, pin) values (52, '54659 Fuller Junction', 'Portland', 'Oregon', 'United States', '97296');
insert into address (student_id, house_number, city, state, country, pin) values (53, '63 Waubesa Lane', 'Brooklyn', 'New York', 'United States', '11220');
insert into address (student_id, house_number, city, state, country, pin) values (54, '6 Grim Terrace', 'Madison', 'Wisconsin', 'United States', '53716');
insert into address (student_id, house_number, city, state, country, pin) values (55, '09 Northfield Center', 'Hartford', 'Connecticut', 'United States', '06160');
insert into address (student_id, house_number, city, state, country, pin) values (56, '42684 Porter Junction', 'Athens', 'Georgia', 'United States', '30610');
insert into address (student_id, house_number, city, state, country, pin) values (57, '0 Stoughton Street', 'Vero Beach', 'Florida', 'United States', '32964');
insert into address (student_id, house_number, city, state, country, pin) values (58, '71 Norway Maple Center', 'Flint', 'Michigan', 'United States', '48505');
insert into address (student_id, house_number, city, state, country, pin) values (59, '551 Coolidge Trail', 'Boise', 'Idaho', 'United States', '83705');
insert into address (student_id, house_number, city, state, country, pin) values (60, '5 Tomscot Way', 'El Paso', 'Texas', 'United States', '79945');
insert into address (student_id, house_number, city, state, country, pin) values (61, '3460 Dakota Center', 'Denver', 'Colorado', 'United States', '80204');
insert into address (student_id, house_number, city, state, country, pin) values (62, '1642 Westend Road', 'Richmond', 'Virginia', 'United States', '23293');
insert into address (student_id, house_number, city, state, country, pin) values (63, '54 Ridgeview Avenue', 'Kansas City', 'Kansas', 'United States', '66112');
insert into address (student_id, house_number, city, state, country, pin) values (64, '763 Meadow Ridge Drive', 'Salt Lake City', 'Utah', 'United States', '84152');
insert into address (student_id, house_number, city, state, country, pin) values (65, '90360 Heffernan Alley', 'Colorado Springs', 'Colorado', 'United States', '80945');
insert into address (student_id, house_number, city, state, country, pin) values (66, '6572 Vermont Center', 'Saginaw', 'Michigan', 'United States', '48609');
insert into address (student_id, house_number, city, state, country, pin) values (67, '78 Barby Way', 'Palm Bay', 'Florida', 'United States', '32909');
insert into address (student_id, house_number, city, state, country, pin) values (68, '890 Mariners Cove Park', 'Boise', 'Idaho', 'United States', '83732');
insert into address (student_id, house_number, city, state, country, pin) values (69, '8201 Debs Circle', 'New York City', 'New York', 'United States', '10184');
insert into address (student_id, house_number, city, state, country, pin) values (70, '3 Sugar Pass', 'Edmond', 'Oklahoma', 'United States', '73034');
insert into address (student_id, house_number, city, state, country, pin) values (71, '548 Butternut Terrace', 'Tacoma', 'Washington', 'United States', '98442');
insert into address (student_id, house_number, city, state, country, pin) values (72, '5277 Duke Drive', 'North Port', 'Florida', 'United States', '34290');
insert into address (student_id, house_number, city, state, country, pin) values (73, '3 Pankratz Hill', 'Detroit', 'Michigan', 'United States', '48232');
insert into address (student_id, house_number, city, state, country, pin) values (74, '43934 Sutteridge Road', 'Kansas City', 'Missouri', 'United States', '64136');
insert into address (student_id, house_number, city, state, country, pin) values (75, '44 Miller Road', 'Florence', 'South Carolina', 'United States', '29505');
insert into address (student_id, house_number, city, state, country, pin) values (76, '8 Hoepker Drive', 'Fort Lauderdale', 'Florida', 'United States', '33315');
insert into address (student_id, house_number, city, state, country, pin) values (77, '92152 Dunning Road', 'Oklahoma City', 'Oklahoma', 'United States', '73119');
insert into address (student_id, house_number, city, state, country, pin) values (78, '9124 Dahle Plaza', 'Omaha', 'Nebraska', 'United States', '68124');
insert into address (student_id, house_number, city, state, country, pin) values (79, '14043 Petterle Junction', 'Dearborn', 'Michigan', 'United States', '48126');
insert into address (student_id, house_number, city, state, country, pin) values (80, '221 Old Shore Junction', 'Kalamazoo', 'Michigan', 'United States', '49048');
insert into address (student_id, house_number, city, state, country, pin) values (81, '748 Pankratz Center', 'Colorado Springs', 'Colorado', 'United States', '80915');
insert into address (student_id, house_number, city, state, country, pin) values (82, '0253 Warner Hill', 'Las Vegas', 'Nevada', 'United States', '89115');
insert into address (student_id, house_number, city, state, country, pin) values (83, '60933 Goodland Place', 'Miami', 'Florida', 'United States', '33147');
insert into address (student_id, house_number, city, state, country, pin) values (84, '89 Schmedeman Hill', 'Modesto', 'California', 'United States', '95397');
insert into address (student_id, house_number, city, state, country, pin) values (85, '871 Village Green Road', 'Chicago', 'Illinois', 'United States', '60646');
insert into address (student_id, house_number, city, state, country, pin) values (86, '13 Russell Street', 'South Bend', 'Indiana', 'United States', '46699');
insert into address (student_id, house_number, city, state, country, pin) values (87, '07 Badeau Trail', 'Roanoke', 'Virginia', 'United States', '24040');
insert into address (student_id, house_number, city, state, country, pin) values (88, '792 Sachtjen Hill', 'Richmond', 'Virginia', 'United States', '23225');
insert into address (student_id, house_number, city, state, country, pin) values (89, '82 Hallows Place', 'Cincinnati', 'Ohio', 'United States', '45238');
insert into address (student_id, house_number, city, state, country, pin) values (90, '0 Michigan Alley', 'Wichita', 'Kansas', 'United States', '67215');
insert into address (student_id, house_number, city, state, country, pin) values (91, '773 Waxwing Alley', 'Colorado Springs', 'Colorado', 'United States', '80945');
insert into address (student_id, house_number, city, state, country, pin) values (92, '71620 Westend Road', 'Sarasota', 'Florida', 'United States', '34276');
insert into address (student_id, house_number, city, state, country, pin) values (93, '16049 Alpine Plaza', 'Miami', 'Florida', 'United States', '33164');
insert into address (student_id, house_number, city, state, country, pin) values (94, '73298 Grim Trail', 'Miami Beach', 'Florida', 'United States', '33141');
insert into address (student_id, house_number, city, state, country, pin) values (95, '049 Lukken Hill', 'Portsmouth', 'Virginia', 'United States', '23705');
insert into address (student_id, house_number, city, state, country, pin) values (96, '9101 Schurz Street', 'Paterson', 'New Jersey', 'United States', '07505');
insert into address (student_id, house_number, city, state, country, pin) values (97, '7 7th Road', 'Washington', 'District of Columbia', 'United States', '20508');
insert into address (student_id, house_number, city, state, country, pin) values (98, '4143 Maryland Court', 'Greensboro', 'North Carolina', 'United States', '27404');
insert into address (student_id, house_number, city, state, country, pin) values (99, '34507 Dennis Park', 'New Orleans', 'Louisiana', 'United States', '70183');
insert into address (student_id, house_number, city, state, country, pin) values (100, '234 Truax Terrace', 'Chicago', 'Illinois', 'United States', '60663');
